/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Acknowledgment: typeof import('./theme/components/acknowledgment/Acknowledgment.vue')['default']
    ArtDot: typeof import('./theme/components/art/ArtDot.vue')['default']
    Aside: typeof import('./theme/components/Aside.vue')['default']
    Breadcrumb: typeof import('./theme/components/Breadcrumb.vue')['default']
    ColorAppearance: typeof import('./theme/components/color-pick/ColorAppearance.vue')['default']
    ColorPick: typeof import('./theme/components/color-pick/ColorPick.vue')['default']
    ColorPickPill: typeof import('./theme/components/color-pick/ColorPickPill.vue')['default']
    Community: typeof import('./theme/components/community/Community.vue')['default']
    DotPattern: typeof import('./theme/components/DotPattern.vue')['default']
    Footer: typeof import('./theme/components/Footer.vue')['default']
    FrameworkCard: typeof import('./theme/components/framework/FrameworkCard.vue')['default']
    GridPattern: typeof import('./theme/components/GridPattern.vue')['default']
    Header: typeof import('./theme/components/Header.vue')['default']
    HomeCodeGranular: typeof import('./theme/components/home/HomeCodeGranular.vue')['default']
    HomeCodeUnstyle: typeof import('./theme/components/home/HomeCodeUnstyle.vue')['default']
    HomeDemo: typeof import('./theme/components/home/HomeDemo.vue')['default']
    HomeFeatures: typeof import('./theme/components/home/HomeFeatures.vue')['default']
    Item: typeof import('./theme/components/blog/Item.vue')['default']
    LandingBackground: typeof import('./theme/components/LandingBackground.vue')['default']
    Lightning: typeof import('./theme/components/Lightning.vue')['default']
    Line: typeof import('./theme/components/Line.vue')['default']
    Logo: typeof import('./theme/components/Logo.vue')['default']
    Next: typeof import('./theme/components/Page/Next.vue')['default']
    Package: typeof import('./theme/components/packages/Package.vue')['default']
    Page: typeof import('./theme/components/Page/Page.vue')['default']
    ParticlesEffect: typeof import('./theme/components/ParticlesEffect.vue')['default']
    Popover: typeof import('./theme/components/Popover.vue')['default']
    Prev: typeof import('./theme/components/Page/Prev.vue')['default']
    RadiusPill: typeof import('./theme/components/color-pick/RadiusPill.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./theme/components/Search.vue')['default']
    Toc: typeof import('./theme/components/toc/Toc.vue')['default']
    TocItem: typeof import('./theme/components/toc/TocItem.vue')['default']
  }
}
